import type { PurchaseOrder } from "./purchase-order-service";

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    pdfName: "23953814 - 5163.pdf",
    finalLinesOutput: [
      {
        json: {
          itemNo: "BH-HEATCORE",
          code: "56024",
          itemDescription: "HEATCORE 4 IN 1 RETROFIT BATHROOM HEATER",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM56024",
          poDescription: "BATHROOM HEATER 4IN1 WHITE RETROFIT HEATCORE - 56024",
          quantity: 10,
          unitprice: 125.13,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
      {
        json: {
          itemNo: "BH-HEATCORE",
          code: "56025",
          itemDescription: "HEATCORE 4 IN 1 RETROFIT BATHROOM HEATER",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM56025",
          poDescription: "BATHROOM HEATER 4IN1 BLACK RETROFIT HEATCORE - 56025",
          quantity: 2,
          unitprice: 125.13,
          shipmentDate: "",
        },
        pairedItem: { item: 1 },
      },
      {
        json: {
          itemNo: "BH-ORBIS",
          code: "56021",
          itemDescription: "ORBIS 4 IN 1 RETROFIT BATHROOM HEATER",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM56021",
          poDescription: "BATHROOM HEATER 4IN1 WHITE RETROFIT ORBIS - 56021",
          quantity: 5,
          unitprice: 139.43,
          shipmentDate: "",
        },
        pairedItem: { item: 2 },
      },
      {
        json: {
          itemNo: "BH-AIRSWAY",
          code: "56013",
          itemDescription: "AIRSWAY 6 IN 1 PREMIUM SLIMLINE BATHROOM HEATER",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM56013",
          poDescription:
            "BATHROOM HEATER 4IN1 SLIMLINE WHITE BH-AIRSWAY - 56013",
          quantity: 10,
          unitprice: 250.25,
          shipmentDate: "",
        },
        pairedItem: { item: 3 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-08-28",
      postingDate: null,
      customerId: "REXPORT",
      customerNumber: "REXPORT",
      customerName: "Rexel Port Pirie [5163]",
      billToName: "Rexel Electrical Supplies",
      billToCustomerNumber: "",
      shipToName: "Rexel Port Pirie",
      sellToAddressLine1: "81 Esmond Road",
      billToAddressLine1: "81 Esmond Road",
      shipToAddressLine1: "81 Esmond Road",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: "RGA Agreement-60 DAYS",
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-08-28",
      totalAmountExcludingTax: "4701.21",
      totalTaxAmount: "470.13",
      totalAmountIncludingTax: "5171.34",
      sellToCity: "PORT PIRIE",
    },
    created_at: "2025-09-24 05:43:54.870331+00",
  },

  {
    pdfName: "578-109595-0.pdf",
    finalLinesOutput: [
      {
        json: {
          itemNo: "CELL-13-5CCT-D75",
          code: "21680",
          itemDescription: "CELL 13W LED LAMP KIT 60D 5CCT D75",
          unitOfMeasureCode: "PCS",
          poItemNumber: "21680",
          poDescription: "LED Downlight Dim 13W 5-CCT 75mm C/O White IP44",
          quantity: 15,
          unitprice: 59.6,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "CETNAJARM",
      customerNumber: "CETNAJARM",
      customerName: "Cetnaj MML - Armidale [578]",
      billToName: "Cetnaj J",
      billToCustomerNumber: "",
      shipToName: "Cetnaj J",
      sellToAddressLine1: "173 Rusden Street",
      billToAddressLine1: "173 Rusden Street",
      shipToAddressLine1: "173 Rusden Street",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-09-12",
      totalAmountExcludingTax: "894",
      totalTaxAmount: "89.4",
      totalAmountIncludingTax: "983.4",
      sellToCity: "ARMIDALE",
    },
    created_at: "2025-09-24 05:43:54.870331+00",
  },
  {
    pdfName: "Cin7_PurchaseOrder_52124_PO-52124_12_Sep_2025_308_PM.pdf",
    finalLinesOutput: [
      {
        json: {
          itemNo: "SWAP-8-ST",
          code: "21453",
          itemDescription: "SWAP-STEP 8W 90MM CRI80 LED TRIO DOWNLIGHT",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DL-21453",
          poDescription:
            "Domus SWAP-8-STEP - 8W LED Tri-Colour Dimmable Step Deepset Trim LED Downlight",
          quantity: 1,
          unitprice: 10.32,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "LMORE",
      customerNumber: "LMORE",
      customerName: "Lighting and More Pty Ltd ",
      billToName: "Ozlighting",
      billToCustomerNumber: "",
      shipToName: "Ozlighting",
      sellToAddressLine1: "29 - 31 Richland Street",
      billToAddressLine1: "29-31 Richland St",
      shipToAddressLine1: "29 - 31 Richland Street",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: null,
      totalAmountExcludingTax: "10.32",
      totalTaxAmount: "1.03",
      totalAmountIncludingTax: "11.35",
      sellToCity: "KINGSGROVE",
    },
    created_at: "2025-09-24 05:43:54.870331+00",
  },
  {
    pdfName: "LS13905 DOMUS - ULTRA URGENT - THANKS JUDY 12.9.25.pdf",
    finalLinesOutput: [
      {
        json: {
          itemNo: "055-GLOBE-R63",
          code: "3000K",
          itemDescription: "7W LED E27 R63 REFLECTOR GLOBE 240V",
          unitOfMeasureCode: "PCS",
          poItemNumber: "19884-COMO-6-GREY",
          poDescription: "IP65 WALL LUMINAIRE 6W - 240V GRY - 3000K",
          quantity: 2,
          unitprice: 170,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-08-11",
      postingDate: null,
      customerId: "LSCOPE",
      customerNumber: "LSCOPE",
      customerName: "Lightscope Pty Ltd",
      billToName: "Lightscope Pty Ltd",
      billToCustomerNumber: "",
      shipToName: "Lightscope Pty Ltd",
      sellToAddressLine1: "Unit 7 / 3 - 5 Deakin Street",
      billToAddressLine1: "Unit 7 / 3-5 Deakin St",
      shipToAddressLine1: "Unit 7 / 3 - 5 Deakin Street",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-08-14",
      totalAmountExcludingTax: "340",
      totalTaxAmount: "34",
      totalAmountIncludingTax: "374",
      sellToCity: "BRENDALE",
    },
    created_at: "2025-09-24 05:43:54.870331+00",
  },
  {
    pdfName: "Purchase Order 90213750.pdf",
    finalLinesOutput: [
      {
        json: {
          itemNo: "ZOOM-PRO-5",
          code: "25702",
          itemDescription: "ZOOM-PRO 5W 12/24V DC GARDEN SPIKE C/W HOOD BLK",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM25702",
          poDescription: "ZOOM PRO 5W 12-24VDC LED SPIKE TRI IP67",
          quantity: 20,
          unitprice: 18,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
      {
        json: {
          itemNo: "STRIKE-60",
          code: "60137",
          itemDescription: "STRIKE 60 INCH DC 3 BLADE CEILING FAN",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM60137",
          poDescription: "STRIKE 60 DC 3 BLADE CEILING FAN BLK/WNT",
          quantity: 3,
          unitprice: 200,
          shipmentDate: "",
        },
        pairedItem: { item: 1 },
      },
      {
        json: {
          itemNo: "STRIKE-48",
          code: "60132",
          itemDescription: "STRIKE 48 INCH DC 3 BLADE CEILING FAN",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM60132",
          poDescription: "STRIKE 48 DC 3 BLADE CEILING FAN BLK/WNT",
          quantity: 1,
          unitprice: 211.04,
          shipmentDate: "",
        },
        pairedItem: { item: 2 },
      },
      {
        json: {
          itemNo: "STRIKE-60",
          code: "60135",
          itemDescription: "STRIKE 60 INCH DC 3 BLADE CEILING FAN",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM60135",
          poDescription: "STRIKE 60 DC 3 BLADE CEILING FAN WHITE",
          quantity: 3,
          unitprice: 200,
          shipmentDate: "",
        },
        pairedItem: { item: 3 },
      },
      {
        json: {
          itemNo: "STRIKE-60",
          code: "60136",
          itemDescription: "STRIKE 60 INCH DC 3 BLADE CEILING FAN",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM60136",
          poDescription: "STRIKE 60 DC 3 BLADE CEILING FAN BLACK",
          quantity: 3,
          unitprice: 200,
          shipmentDate: "",
        },
        pairedItem: { item: 4 },
      },
      {
        json: {
          itemNo: "STRIKE-LIGHT-KIT",
          code: "60141",
          itemDescription: "STRIKE CEILING FAN LED TRIO LIGHT KIT",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM60141",
          poDescription: "STRIKE LED LIGHT KIT 18W TRI COLOUR BLK",
          quantity: 3,
          unitprice: 42,
          shipmentDate: "",
        },
        pairedItem: { item: 5 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "LIGHHTOO",
      customerNumber: "LIGHHTOO",
      customerName: "The Lighthouse Co P/L Toowoomba",
      billToName: "THE LIGHT HOUSE COMPANY PTY LTD",
      billToCustomerNumber: "",
      shipToName: "THE LIGHT HOUSE COMPANY P/L",
      sellToAddressLine1: "8/12 Prescott st",
      billToAddressLine1: "8/12 PRESCOTT ST",
      shipToAddressLine1: "8/12 Prescott st",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-09-12",
      totalAmountExcludingTax: "2497.04",
      totalTaxAmount: null,
      totalAmountIncludingTax: null,
      sellToCity: "TOOWOOMBA",
    },
    created_at: "2025-09-24 05:43:54.870331+00",
  },
  {
    pdfName: "Purchase Order 14960718.pdf",
    finalLinesOutput: [
      {
        json: {
          itemNo: "Ambiguity in identification",
          code: "Ambiguity in identification",
          itemDescription: "Ambiguity in identification",
          unitOfMeasureCode: "",
          poItemNumber: "2688",
          poDescription: "FREIGHT & CHARGES",
          quantity: 1,
          unitprice: 25,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
      {
        json: {
          itemNo: "ASTRA-4-BLK",
          code: "21284",
          itemDescription: "ASTRA CABINET 3.6W 12V DC BLK",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM21284",
          poDescription:
            "BI PROJECT LIGHT 25 DOM21284 ASTRA CABINET LIGHT 3K BLK",
          quantity: 4,
          unitprice: 15,
          shipmentDate: "",
        },
        pairedItem: { item: 1 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "CNWNGE",
      customerNumber: "CNWNGE",
      customerName: "CNW P/L North Geelong [149]",
      billToName: "CNW PTY LTD - GEELONG",
      billToCustomerNumber: "",
      shipToName: "CNW GEELONG",
      sellToAddressLine1: "1 Sharon court",
      billToAddressLine1: "1 Sharon Court",
      shipToAddressLine1: "1 Sharon court",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-09-12",
      totalAmountExcludingTax: "85",
      totalTaxAmount: null,
      totalAmountIncludingTax: null,
      sellToCity: "NORTH GEELONG",
    },
    created_at: "2025-09-24 05:43:54.870331+00",
  },
  {
    pdfName: "S1001256-PURCHASE ORDER-1718316.pdf",
    finalLinesOutput: [
      {
        json: {
          itemNo: "CHESTER-PTOP",
          code: "15034",
          itemDescription: "CHESTER POST TOP B22",
          unitOfMeasureCode: "PCS",
          poItemNumber: "15034",
          poDescription: "DNS15034:CHESTER POST TOP B22WHITE",
          quantity: 1,
          unitprice: 135,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
      {
        json: {
          itemNo: "AP-6020",
          code: "10836",
          itemDescription: "AP-6020 60MM X 2.0M ALUMINIUM POST",
          unitOfMeasureCode: "PCS",
          poItemNumber: "B10836",
          poDescription:
            "DNSB10836: AP-6020 60MM X 2.0M ALUMINIUM POST - BURGUNDY",
          quantity: 1,
          unitprice: 160.4,
          shipmentDate: "",
        },
        pairedItem: { item: 1 },
      },
      {
        json: {
          itemNo: "Ambiguity in identification",
          code: "Ambiguity in identification",
          itemDescription: "Ambiguity in identification",
          unitOfMeasureCode: "",
          poItemNumber: "undefined",
          poDescription: "Freight Supplier Charge",
          quantity: 1,
          unitprice: 20,
          shipmentDate: "",
        },
        pairedItem: { item: 2 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "MIDDROS",
      customerNumber: "MIDDROS",
      customerName: "Middys Rosebud [3220]",
      billToName: "MIDDENDORP ELECTRIC CO. PTY. LTD.",
      billToCustomerNumber: "",
      shipToName: "Middy's Rosebud",
      sellToAddressLine1: "212 Boneo Rd",
      billToAddressLine1: "PO Box 328",
      shipToAddressLine1: "212 Boneo Rd",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-09-15",
      totalAmountExcludingTax: "315.4",
      totalTaxAmount: "31.54",
      totalAmountIncludingTax: "346.94",
      sellToCity: "ROSEBUD",
    },
    created_at: "2025-09-24 05:43:54.870331+00",
  },
  {
    pdfName: "E89B8573-8C95-4C40-91A8-E53ABB2B5D1F.pdf",
    finalLinesOutput: [
      {
        json: {
          itemNo: "DECO-28-WHT",
          code: "20434",
          itemDescription: "DECO-28 RND 28W LED KIT WHT",
          unitOfMeasureCode: "PCS",
          poItemNumber: "20434",
          poDescription:
            "20434 DECO-28-TRIO 228MM DIFFUSED DOWNLIGHT WHITE SURROUND 28 WATT LED TRICOLOUR",
          quantity: 1,
          unitprice: 71.28,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
      {
        json: {
          itemNo: "BLISS-10-WHT",
          code: "20706",
          itemDescription: "BLISS-10 RND 10W LED D/L WHT",
          unitOfMeasureCode: "PCS",
          poItemNumber: "20706",
          poDescription:
            "DOMUS BLISS 10W ROUND LED D/L WHITE TRIO BLISS-10-WHITE 20706",
          quantity: 22,
          unitprice: 10.62,
          shipmentDate: "",
        },
        pairedItem: { item: 1 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "HGENBRO",
      customerNumber: "HGENBRO",
      customerName: "Hardware & General Brookvale",
      billToName: "Hardware & General Supplies Limited",
      billToCustomerNumber: "",
      shipToName: "H&G Lighting & Electrical",
      sellToAddressLine1: "64 Winbourne Road",
      billToAddressLine1: "702-704 Pittwater Road",
      shipToAddressLine1: "64 Winbourne Road",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-09-14",
      totalAmountExcludingTax: "304.92",
      totalTaxAmount: null,
      totalAmountIncludingTax: null,
      sellToCity: "BROOKVALE",
    },
    created_at: "2025-09-24 05:43:54.870331+00",
  },
];
