import type { PurchaseOrder } from "./purchase-order-service"

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    pdfName: "23953814 - 5163.pdf",
    poNumber: "23953814",
    finalLinesOutput: [
      {
        json: {
          itemNo: "BH-HEATCORE",
          code: "56024",
          itemDescription: "HEATCORE 4 IN 1 RETROFIT BATHROOM HEATER",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM56024",
          poDescription: "BATHROOM HEATER 4IN1 WHITE RETROFIT HEATCORE - 56024",
          quantity: 10,
          unitprice: 125.13,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
      {
        json: {
          itemNo: "BH-HEATCORE",
          code: "56025",
          itemDescription: "HEATCORE 4 IN 1 RETROFIT BATHROOM HEATER",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM56025",
          poDescription: "BATHROOM HEATER 4IN1 BLACK RETROFIT HEATCORE - 56025",
          quantity: 2,
          unitprice: 125.13,
          shipmentDate: "",
        },
        pairedItem: { item: 1 },
      },
      {
        json: {
          itemNo: "BH-ORBIS",
          code: "56021",
          itemDescription: "ORBIS 4 IN 1 RETROFIT BATHROOM HEATER",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM56021",
          poDescription: "BATHROOM HEATER 4IN1 WHITE RETROFIT ORBIS - 56021",
          quantity: 5,
          unitprice: 139.43,
          shipmentDate: "",
        },
        pairedItem: { item: 2 },
      },
      {
        json: {
          itemNo: "BH-AIRSWAY",
          code: "56013",
          itemDescription: "AIRSWAY 6 IN 1 PREMIUM SLIMLINE BATHROOM HEATER",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM56013",
          poDescription: "BATHROOM HEATER 4IN1 SLIMLINE WHITE BH-AIRSWAY - 56013",
          quantity: 10,
          unitprice: 250.25,
          shipmentDate: "",
        },
        pairedItem: { item: 3 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-08-28",
      postingDate: null,
      customerId: "REXPORT",
      customerNumber: "REXPORT",
      customerName: "Rexel Port Pirie [5163]",
      billToName: "Rexel Electrical Supplies",
      billToCustomerNumber: "",
      shipToName: "Rexel Port Pirie",
      sellToAddressLine1: "81 Esmond Road",
      billToAddressLine1: "81 Esmond Road",
      shipToAddressLine1: "81 Esmond Road",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: "RGA Agreement-60 DAYS",
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-08-28",
      totalAmountExcludingTax: "4701.21",
      totalTaxAmount: "470.13",
      totalAmountIncludingTax: "5171.34",
      sellToCity: "PORT PIRIE",
    },
    created_at: "2025-09-25 05:43:54.870331+00",
  },

  {
    pdfName: "578-109595-0.pdf",
    poNumber: "578-109595-0",
    finalLinesOutput: [
      {
        json: {
          itemNo: "CELL-13-5CCT-D75",
          code: "21680",
          itemDescription: "CELL 13W LED LAMP KIT 60D 5CCT D75",
          unitOfMeasureCode: "PCS",
          poItemNumber: "21680",
          poDescription: "LED Downlight Dim 13W 5-CCT 75mm C/O White IP44",
          quantity: 15,
          unitprice: 59.6,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "CETNAJARM",
      customerNumber: "CETNAJARM",
      customerName: "Cetnaj MML - Armidale [578]",
      billToName: "Cetnaj J",
      billToCustomerNumber: "",
      shipToName: "Cetnaj J",
      sellToAddressLine1: "173 Rusden Street",
      billToAddressLine1: "173 Rusden Street",
      shipToAddressLine1: "173 Rusden Street",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-09-12",
      totalAmountExcludingTax: "894",
      totalTaxAmount: "89.4",
      totalAmountIncludingTax: "983.4",
      sellToCity: "ARMIDALE",
    },
    created_at: "2025-09-25 05:43:54.870331+00",
  },
  {
    pdfName: "Cin7_PurchaseOrder_52124_PO-52124_12_Sep_2025_308_PM.pdf",
    poNumber: "PO-52124",
    finalLinesOutput: [
      {
        json: {
          itemNo: "SWAP-8-ST",
          code: "21453",
          itemDescription: "SWAP-STEP 8W 90MM CRI80 LED TRIO DOWNLIGHT",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DL-21453",
          poDescription: "Domus SWAP-8-STEP - 8W LED Tri-Colour Dimmable Step Deepset Trim LED Downlight",
          quantity: 1,
          unitprice: 10.32,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "LMORE",
      customerNumber: "LMORE",
      customerName: "Lighting and More Pty Ltd ",
      billToName: "Ozlighting",
      billToCustomerNumber: "",
      shipToName: "Ozlighting",
      sellToAddressLine1: "29 - 31 Richland Street",
      billToAddressLine1: "29-31 Richland St",
      shipToAddressLine1: "29 - 31 Richland Street",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: null,
      totalAmountExcludingTax: "10.32",
      totalTaxAmount: "1.03",
      totalAmountIncludingTax: "11.35",
      sellToCity: "KINGSGROVE",
    },
    created_at: "2025-09-25 05:43:54.870331+00",
  },
  {
    pdfName: "LS13905 DOMUS - ULTRA URGENT - THANKS JUDY 12.9.25.pdf",
    poNumber: "LS13905",
    finalLinesOutput: [
      {
        json: {
          itemNo: "055-GLOBE-R63",
          code: "3000K",
          itemDescription: "7W LED E27 R63 REFLECTOR GLOBE 240V",
          unitOfMeasureCode: "PCS",
          poItemNumber: "19884-COMO-6-GREY",
          poDescription: "IP65 WALL LUMINAIRE 6W - 240V GRY - 3000K",
          quantity: 2,
          unitprice: 170,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-08-11",
      postingDate: null,
      customerId: "LSCOPE",
      customerNumber: "LSCOPE",
      customerName: "Lightscope Pty Ltd",
      billToName: "Lightscope Pty Ltd",
      billToCustomerNumber: "",
      shipToName: "Lightscope Pty Ltd",
      sellToAddressLine1: "Unit 7 / 3 - 5 Deakin Street",
      billToAddressLine1: "Unit 7 / 3-5 Deakin St",
      shipToAddressLine1: "Unit 7 / 3 - 5 Deakin Street",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-08-14",
      totalAmountExcludingTax: "340",
      totalTaxAmount: "34",
      totalAmountIncludingTax: "374",
      sellToCity: "BRENDALE",
    },
    created_at: "2025-09-25 05:43:54.870331+00",
  },
  {
    pdfName: "Purchase Order 90213750.pdf",
    poNumber: "90213750",
    finalLinesOutput: [
      {
        json: {
          itemNo: "ZOOM-PRO-5",
          code: "25702",
          itemDescription: "ZOOM-PRO 5W 12/24V DC GARDEN SPIKE C/W HOOD BLK",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM25702",
          poDescription: "ZOOM PRO 5W 12-24VDC LED SPIKE TRI IP67",
          quantity: 20,
          unitprice: 18,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
      {
        json: {
          itemNo: "STRIKE-60",
          code: "60137",
          itemDescription: "STRIKE 60 INCH DC 3 BLADE CEILING FAN",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM60137",
          poDescription: "STRIKE 60 DC 3 BLADE CEILING FAN BLK/WNT",
          quantity: 3,
          unitprice: 200,
          shipmentDate: "",
        },
        pairedItem: { item: 1 },
      },
      {
        json: {
          itemNo: "STRIKE-48",
          code: "60132",
          itemDescription: "STRIKE 48 INCH DC 3 BLADE CEILING FAN",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM60132",
          poDescription: "STRIKE 48 DC 3 BLADE CEILING FAN BLK/WNT",
          quantity: 1,
          unitprice: 211.04,
          shipmentDate: "",
        },
        pairedItem: { item: 2 },
      },
      {
        json: {
          itemNo: "STRIKE-60",
          code: "60135",
          itemDescription: "STRIKE 60 INCH DC 3 BLADE CEILING FAN",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM60135",
          poDescription: "STRIKE 60 DC 3 BLADE CEILING FAN WHITE",
          quantity: 3,
          unitprice: 200,
          shipmentDate: "",
        },
        pairedItem: { item: 3 },
      },
      {
        json: {
          itemNo: "STRIKE-60",
          code: "60136",
          itemDescription: "STRIKE 60 INCH DC 3 BLADE CEILING FAN",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM60136",
          poDescription: "STRIKE 60 DC 3 BLADE CEILING FAN BLACK",
          quantity: 3,
          unitprice: 200,
          shipmentDate: "",
        },
        pairedItem: { item: 4 },
      },
      {
        json: {
          itemNo: "STRIKE-LIGHT-KIT",
          code: "60141",
          itemDescription: "STRIKE CEILING FAN LED TRIO LIGHT KIT",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM60141",
          poDescription: "STRIKE LED LIGHT KIT 18W TRI COLOUR BLK",
          quantity: 3,
          unitprice: 42,
          shipmentDate: "",
        },
        pairedItem: { item: 5 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "LIGHHTOO",
      customerNumber: "LIGHHTOO",
      customerName: "The Lighthouse Co P/L Toowoomba",
      billToName: "THE LIGHT HOUSE COMPANY PTY LTD",
      billToCustomerNumber: "",
      shipToName: "THE LIGHT HOUSE COMPANY P/L",
      sellToAddressLine1: "8/12 Prescott st",
      billToAddressLine1: "8/12 PRESCOTT ST",
      shipToAddressLine1: "8/12 Prescott st",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-09-12",
      totalAmountExcludingTax: "2497.04",
      totalTaxAmount: null,
      totalAmountIncludingTax: null,
      sellToCity: "TOOWOOMBA",
    },
    created_at: "2025-09-25 05:43:54.870331+00",
  },
  {
    pdfName: "Purchase Order 14960718.pdf",
    poNumber: "14960718",
    finalLinesOutput: [
      {
        json: {
          itemNo: "Ambiguity in identification",
          code: "Ambiguity in identification",
          itemDescription: "Ambiguity in identification",
          unitOfMeasureCode: "",
          poItemNumber: "2688",
          poDescription: "FREIGHT & CHARGES",
          quantity: 1,
          unitprice: 25,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
      {
        json: {
          itemNo: "ASTRA-4-BLK",
          code: "21284",
          itemDescription: "ASTRA CABINET 3.6W 12V DC BLK",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM21284",
          poDescription: "BI PROJECT LIGHT 25 DOM21284 ASTRA CABINET LIGHT 3K BLK",
          quantity: 4,
          unitprice: 15,
          shipmentDate: "",
        },
        pairedItem: { item: 1 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "CNWNGE",
      customerNumber: "CNWNGE",
      customerName: "CNW P/L North Geelong [149]",
      billToName: "CNW PTY LTD - GEELONG",
      billToCustomerNumber: "",
      shipToName: "CNW GEELONG",
      sellToAddressLine1: "1 Sharon court",
      billToAddressLine1: "1 Sharon Court",
      shipToAddressLine1: "1 Sharon court",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-09-12",
      totalAmountExcludingTax: "85",
      totalTaxAmount: null,
      totalAmountIncludingTax: null,
      sellToCity: "NORTH GEELONG",
    },
    created_at: "2025-09-25 05:43:54.870331+00",
  },
  {
    pdfName: "S1001256-PURCHASE ORDER-1718316.pdf",
    poNumber: "1718316",
    finalLinesOutput: [
      {
        json: {
          itemNo: "CHESTER-PTOP",
          code: "15034",
          itemDescription: "CHESTER POST TOP B22",
          unitOfMeasureCode: "PCS",
          poItemNumber: "15034",
          poDescription: "DNS15034:CHESTER POST TOP B22WHITE",
          quantity: 1,
          unitprice: 135,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
      {
        json: {
          itemNo: "AP-6020",
          code: "10836",
          itemDescription: "AP-6020 60MM X 2.0M ALUMINIUM POST",
          unitOfMeasureCode: "PCS",
          poItemNumber: "B10836",
          poDescription: "DNSB10836: AP-6020 60MM X 2.0M ALUMINIUM POST - BURGUNDY",
          quantity: 1,
          unitprice: 160.4,
          shipmentDate: "",
        },
        pairedItem: { item: 1 },
      },
      {
        json: {
          itemNo: "Ambiguity in identification",
          code: "Ambiguity in identification",
          itemDescription: "Ambiguity in identification",
          unitOfMeasureCode: "",
          poItemNumber: "undefined",
          poDescription: "Freight Supplier Charge",
          quantity: 1,
          unitprice: 20,
          shipmentDate: "",
        },
        pairedItem: { item: 2 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "MIDDROS",
      customerNumber: "MIDDROS",
      customerName: "Middys Rosebud [3220]",
      billToName: "MIDDENDORP ELECTRIC CO. PTY. LTD.",
      billToCustomerNumber: "",
      shipToName: "Middy's Rosebud",
      sellToAddressLine1: "212 Boneo Rd",
      billToAddressLine1: "PO Box 328",
      shipToAddressLine1: "212 Boneo Rd",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-09-15",
      totalAmountExcludingTax: "315.4",
      totalTaxAmount: "31.54",
      totalAmountIncludingTax: "346.94",
      sellToCity: "ROSEBUD",
    },
    created_at: "2025-09-24 05:43:54.870331+00",
  },
  {
    pdfName: "E89B8573-8C95-4C40-91A8-E53ABB2B5D1F.pdf",
    poNumber: "81867501",
    finalLinesOutput: [
      {
        json: {
          itemNo: "DECO-28-WHT",
          code: "20434",
          itemDescription: "DECO-28 RND 28W LED KIT WHT",
          unitOfMeasureCode: "PCS",
          poItemNumber: "20434",
          poDescription: "20434 DECO-28-TRIO 228MM DIFFUSED DOWNLIGHT WHITE SURROUND 28 WATT LED TRICOLOUR",
          quantity: 1,
          unitprice: 71.28,
          shipmentDate: "",
        },
        pairedItem: { item: 0 },
      },
      {
        json: {
          itemNo: "BLISS-10-WHT",
          code: "20706",
          itemDescription: "BLISS-10 RND 10W LED D/L WHT",
          unitOfMeasureCode: "PCS",
          poItemNumber: "20706",
          poDescription: "DOMUS BLISS 10W ROUND LED D/L WHITE TRIO BLISS-10-WHITE 20706",
          quantity: 22,
          unitprice: 10.62,
          shipmentDate: "",
        },
        pairedItem: { item: 1 },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "HGENBRO",
      customerNumber: "HGENBRO",
      customerName: "Hardware & General Brookvale",
      billToName: "Hardware & General Supplies Limited",
      billToCustomerNumber: "",
      shipToName: "H&G Lighting & Electrical",
      sellToAddressLine1: "64 Winbourne Road",
      billToAddressLine1: "702-704 Pittwater Road",
      shipToAddressLine1: "64 Winbourne Road",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-09-14",
      totalAmountExcludingTax: "304.92",
      totalTaxAmount: null,
      totalAmountIncludingTax: null,
      sellToCity: "BROOKVALE",
    },
    created_at: "2025-09-24 05:43:54.870331+00",
  },
  {
    pdfName: "ORD00185110.pdf",
    poNumber: "185110",
    finalLinesOutput: [
      {
        json: {
          itemNo: "ZEKE-8-BLK",
          code: "19542",
          itemDescription: "ZEKE-8W RCT WB 240V BLK",
          unitOfMeasureCode: "PCS",
          poItemNumber: "19542",
          poDescription: "19542-240v 3k",
          quantity: 4,
          unitprice: 87,
          shipmentDate: "",
        },
        pairedItem: {
          item: 0,
        },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "EVERGLOW",
      customerNumber: "EVERGLOW",
      customerName: "Secuview T/A Everglow Lighting",
      billToName: "Everglow LED Lighting",
      billToCustomerNumber: "",
      shipToName: "Everglow LED Lighting",
      sellToAddressLine1: "6/20-26 Sullivan Street",
      billToAddressLine1: "6/20-26 Sullivan Street",
      shipToAddressLine1: "6/20-26 Sullivan Street",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: null,
      totalAmountExcludingTax: "348",
      totalTaxAmount: "34.8",
      totalAmountIncludingTax: "382.8",
      sellToCity: "MOORABBIN",
    },
    created_at: "2025-09-24 06:57:49.975493+00",
  },
  {
    pdfName: "PO 30583.pdf",
    poNumber: "30583",
    finalLinesOutput: [
      {
        json: {
          itemNo: "BLISS-10-WHT",
          code: "20706",
          itemDescription: "BLISS-10 RND 10W LED D/L WHT",
          unitOfMeasureCode: "PCS",
          poItemNumber: "20706",
          poDescription:
            "DOMUS 20706 BLISS-10 ROUND 10W DIMMABLE LED COLOUR CHANGE SWITCHABLE DOWNLIGHT - SATIN WHITE FRAME",
          quantity: 45,
          unitprice: 9.6,
          shipmentDate: "",
        },
        pairedItem: {
          item: 0,
        },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "SCHNAP",
      customerNumber: "SCHNAP",
      customerName: "Schnap Electric Products",
      billToName: "SCHNAP Electric Products",
      billToCustomerNumber: "",
      shipToName: "SCHNAP Electric Products",
      sellToAddressLine1: "3/192A Kingsgrove Rd",
      billToAddressLine1: "3/192A Kingsgrove Rd",
      shipToAddressLine1: "3/192A Kingsgrove Rd",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: null,
      totalAmountExcludingTax: "432",
      totalTaxAmount: "43.2",
      totalAmountIncludingTax: "475.2",
      sellToCity: "KINGSGROVE",
    },
    created_at: "2025-09-24 06:58:55.772828+00",
  },
  {
    pdfName: "Purchase Order 1299603.pdf",
    poNumber: "1299603",
    finalLinesOutput: [
      {
        json: {
          itemNo: "PICO-7-WHT",
          code: "21582",
          itemDescription: "PICO-7 MINI REC RND KIT IP54 UGR19 WHT",
          unitOfMeasureCode: "PCS",
          poItemNumber: "21582",
          poDescription: "DOWNLIGHT PICO 7W 3000K - 4000K - 5700K (SWITCHABLE) 50MM C",
          quantity: 17,
          unitprice: 41,
          shipmentDate: "",
        },
        pairedItem: {
          item: 0,
        },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "LHBUL",
      customerNumber: "LHBUL",
      customerName: "L&H Bulleen [3105]",
      billToName: "Lawrence & Hanson Group Pty Ltd",
      billToCustomerNumber: "",
      shipToName: "L & H - BULLEEN",
      sellToAddressLine1: "204 BULLEEN ROAD",
      billToAddressLine1: "204 BULLEEN ROAD",
      shipToAddressLine1: "204 BULLEEN ROAD",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: "Road",
      salesperson: null,
      requestedDeliveryDate: "2025-09-17",
      totalAmountExcludingTax: "697",
      totalTaxAmount: null,
      totalAmountIncludingTax: "697",
      sellToCity: "BULLEEN",
    },
    created_at: "2025-09-24 07:00:02.095971+00",
  },
  {
    pdfName: "Purchase Order 30953368.pdf",
    poNumber: "30953368",
    finalLinesOutput: [
      {
        json: {
          itemNo: "YOU-3-RND",
          code: "19985",
          itemDescription: "YOU RND 3W 240V WHITE",
          unitOfMeasureCode: "PCS",
          poItemNumber: "BI30925",
          poDescription: "BI30925 DOM 19985",
          quantity: 4,
          unitprice: 61.3,
          shipmentDate: "",
        },
        pairedItem: {
          item: 0,
        },
      },
      {
        json: {
          itemNo: "DECO-8-WHT",
          code: "20410",
          itemDescription: "DECO-8 RND 8W LED KIT WHT",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM20410",
          poDescription: "LED D/LIGHT DECO RND 8W CCT 70MM C/O WHT",
          quantity: 25,
          unitprice: 24.5,
          shipmentDate: "",
        },
        pairedItem: {
          item: 1,
        },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-10",
      postingDate: null,
      customerId: "SHERALB",
      customerNumber: "SHERALB",
      customerName: "Sherriff Albion [309]",
      billToName: "SHERRIFF ELECTRICAL PTY LTD - ALBION",
      billToCustomerNumber: "",
      shipToName: "SHERRIFF ELECTRICAL",
      sellToAddressLine1: "11 ELLIOT STREET",
      billToAddressLine1: "11 ELLIOTT STREET",
      shipToAddressLine1: "11 ELLIOT STREET",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: "2025-09-10",
      totalAmountExcludingTax: "857.7",
      totalTaxAmount: null,
      totalAmountIncludingTax: null,
      sellToCity: "ALBION",
    },
    created_at: "2025-09-24 07:02:37.309762+00",
  },
  {
    pdfName: "Purchase Order GN144642.PDF",
    poNumber: "GN144642",
    finalLinesOutput: [
      {
        json: {
          itemNo: "KEY-G9-TRIO",
          code: "65126",
          itemDescription: "KEY G9 4W 240V TRICOLOUR DIMMABLE CRI90",
          unitOfMeasureCode: "PCS",
          poItemNumber: "DOM65126",
          poDescription: "KEY-G9 TRIO DIMMABLE",
          quantity: 20,
          unitprice: 9,
          shipmentDate: "",
        },
        pairedItem: {
          item: 0,
        },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "ZOLTAN",
      customerNumber: "ZOLTAN",
      customerName: "Zoltan Electrical & Plumbing Services ",
      billToName: "ZOLTAN ELECTRICAL & PLUMBING SUPPLIES",
      billToCustomerNumber: "",
      shipToName: "ZOLTAN ELECTRICAL & PLUMBING SUPPLIES",
      sellToAddressLine1: "399 CONCORD ROAD",
      billToAddressLine1: "399 CONCORD ROAD",
      shipToAddressLine1: "399 CONCORD ROAD",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: null,
      totalAmountExcludingTax: "180",
      totalTaxAmount: "18",
      totalAmountIncludingTax: "198",
      sellToCity: "CONCORD WEST",
    },
    created_at: "2025-09-24 07:05:13.233129+00",
  },
  {
    pdfName: "Purchase Order NW344012.pdf",
    poNumber: "NW344012",
    finalLinesOutput: [
      {
        json: {
          itemNo: "BL-100",
          code: "10700",
          itemDescription: "BL-100 3-TIER BOLLARD HEAD E27",
          unitOfMeasureCode: "PCS",
          poItemNumber: "10700",
          poDescription: "BL-100 3-TIER BOLLARD HEAD E27",
          quantity: 5,
          unitprice: 36.5,
          shipmentDate: "",
        },
        pairedItem: {
          item: 0,
        },
      },
      {
        json: {
          itemNo: "TURIN-PTOP",
          code: "15477",
          itemDescription: "TURIN POST TOP B22",
          unitOfMeasureCode: "PCS",
          poItemNumber: "TEMP500",
          poDescription: "15477 TURIN POST TOP 60MM FT GT439 BLACK",
          quantity: 1,
          unitprice: 135,
          shipmentDate: "",
        },
        pairedItem: {
          item: 1,
        },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-05",
      postingDate: null,
      customerId: "ROVE",
      customerNumber: "ROVE",
      customerName: "Rovert Pty Ltd Newcastle",
      billToName: "Rovert Lighting & Electrical",
      billToCustomerNumber: "",
      shipToName: "ROVERT LTD",
      sellToAddressLine1: "4 BRONTE ROAD",
      billToAddressLine1: "4 BRONTE ROAD",
      shipToAddressLine1: "4 BRONTE ROAD",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: null,
      totalAmountExcludingTax: "317.5",
      totalTaxAmount: null,
      totalAmountIncludingTax: null,
      sellToCity: "BROADMEADOW",
    },
    created_at: "2025-09-24 07:06:10.433067+00",
  },
  {
    pdfName: "PURCHASE_ORDER.PDF",
    poNumber: "A/132791",
    finalLinesOutput: [
      {
        json: {
          itemNo: "SAMSON-FL",
          code: "22830",
          itemDescription: "SAMSON-FL M&C FLOOR LAMP DIM 240V",
          unitOfMeasureCode: "PCS",
          poItemNumber: "22830",
          poDescription: "SAMSON UPLIGHTER MOTHER&SON DIMMABLE BLACK (30W&5W CCT QUAD) STOCK",
          quantity: 2,
          unitprice: 94.4,
          shipmentDate: "",
        },
        pairedItem: {
          item: 0,
        },
      },
    ],
    finalSOHeaderOutput: {
      orderDate: "2025-09-12",
      postingDate: null,
      customerId: "L4UASH",
      customerNumber: "L4UASH",
      customerName: "Lights For You Ashfield",
      billToName: "Lights For You Pty Ltd",
      billToCustomerNumber: "",
      shipToName: "Lights For You Pty Ltd",
      sellToAddressLine1: "433 Liverpool Road",
      billToAddressLine1: "433 Liverpool Road",
      shipToAddressLine1: "433 Liverpool Road",
      currencyCode: "AUD",
      pricesIncludeTax: false,
      paymentTerms: null,
      shipmentMethod: null,
      salesperson: null,
      requestedDeliveryDate: null,
      totalAmountExcludingTax: "188.8",
      totalTaxAmount: null,
      totalAmountIncludingTax: null,
      sellToCity: "ASHFIELD",
    },
    created_at: "2025-09-24 07:07:08.960284+00",
  },
]
